# Generated by Django 6.0.3 on 2026-06-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientesaldofavormovimiento',
            new_name='cartera_cli_cliente_8df3be_idx',
            old_name='cartera_cli_cliente_495953_idx',
        ),
        migrations.RenameIndex(
            model_name='clientesaldofavormovimiento',
            new_name='cartera_cli_tipo_e2c777_idx',
            old_name='cartera_cli_tipo_5a9e96_idx',
        ),
        migrations.RenameIndex(
            model_name='pagoaplicacionnota',
            new_name='cartera_pag_nota_ve_075d83_idx',
            old_name='cartera_pag_nota_ve_20a596_idx',
        ),
        migrations.RenameIndex(
            model_name='pagoaplicacionnota',
            new_name='cartera_pag_pago_id_ae690a_idx',
            old_name='cartera_pag_pago_id_38a88b_idx',
        ),
        migrations.RenameIndex(
            model_name='pagocliente',
            new_name='cartera_pag_cliente_775d29_idx',
            old_name='cartera_pag_cliente_3ea20a_idx',
        ),
        migrations.RenameIndex(
            model_name='pagocliente',
            new_name='cartera_pag_estado_55c3aa_idx',
            old_name='cartera_pag_estado_bbd8a4_idx',
        ),
        migrations.RenameIndex(
            model_name='pagocliente',
            new_name='cartera_pag_tipo_ap_adb64b_idx',
            old_name='cartera_pag_tipo_ap_26105d_idx',
        ),
    ]
