# Generated by Django 6.0.3 on 2026-06-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0005_notaventa_fisica_fk'),
        ('ventas', '0002_notaventa_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoaplicacionnota',
            name='nota_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_cartera', to='ventas.notaventa'),
        ),
    ]
