# Generated by Django 6.0.3 on 2026-06-30 19:52

import cartera.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_alter_pagoaplicacionnota_nota_venta'),
        ('catalogos', '0027_notaventa_fisica_fk'),
        ('ventas', '0002_notaventa_fisica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(db_index=True, max_length=36, verbose_name='UUID fiscal')),
                ('serie', models.CharField(blank=True, max_length=40)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=5)),
                ('moneda', models.CharField(blank=True, max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rfc_emisor', models.CharField(blank=True, max_length=13)),
                ('nombre_emisor', models.CharField(blank=True, max_length=254)),
                ('rfc_receptor', models.CharField(blank=True, max_length=13)),
                ('nombre_receptor', models.CharField(blank=True, max_length=254)),
                ('uso_cfdi', models.CharField(blank=True, max_length=4)),
                ('forma_pago', models.CharField(blank=True, max_length=2)),
                ('metodo_pago', models.CharField(blank=True, max_length=3)),
                ('xml', models.FileField(upload_to=cartera.models.factura_xml_upload_to)),
                ('xml_hash', models.CharField(db_index=True, max_length=64)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('CAN', 'Cancelada')], db_index=True, default='ACT', max_length=3)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_cartera_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cartera', to='catalogos.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_cartera_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de cliente',
                'verbose_name_plural': 'Facturas de clientes',
                'ordering': ['-fecha', '-id'],
                'permissions': [('puede_registrar_facturas', 'Puede registrar facturas'), ('puede_cancelar_facturas', 'Puede cancelar facturas'), ('puede_ver_facturacion', 'Puede ver facturación')],
            },
        ),
        migrations.CreateModel(
            name='FacturaAplicacionNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_facturado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_facturas_cartera_creadas', to=settings.AUTH_USER_MODEL)),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_cartera_aplicadas', to='ventas.notaventa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='cartera.facturacliente')),
            ],
            options={
                'verbose_name': 'Aplicación de factura a nota',
                'verbose_name_plural': 'Aplicaciones de facturas a notas',
                'ordering': ['nota_venta__fecha', 'nota_venta__folio', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='facturacliente',
            index=models.Index(fields=['cliente', 'fecha'], name='cartera_fac_cliente_ae8fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacliente',
            index=models.Index(fields=['estado'], name='cartera_fac_estado_c8c3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacliente',
            index=models.Index(fields=['uuid'], name='cartera_fac_uuid_4cd069_idx'),
        ),
        migrations.AddIndex(
            model_name='facturacliente',
            index=models.Index(fields=['xml_hash'], name='cartera_fac_xml_has_ba505f_idx'),
        ),
        migrations.AddConstraint(
            model_name='facturacliente',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='factura_cliente_total_gt_0'),
        ),
        migrations.AddIndex(
            model_name='facturaaplicacionnota',
            index=models.Index(fields=['factura'], name='cartera_fac_factura_e04d64_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaaplicacionnota',
            index=models.Index(fields=['nota_venta'], name='cartera_fac_nota_ve_985dec_idx'),
        ),
        migrations.AddConstraint(
            model_name='facturaaplicacionnota',
            constraint=models.CheckConstraint(condition=models.Q(('monto_facturado__gt', 0)), name='factura_aplicacion_monto_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='facturaaplicacionnota',
            constraint=models.UniqueConstraint(fields=('factura', 'nota_venta'), name='factura_aplicacion_nota_unica'),
        ),
    ]
