# Generated by Django 5.2.8 on 2025-12-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
