# Generated by Django 5.2.8 on 2026-01-07 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_proyecto_apodo_proyecto_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Física'), ('MORAL', 'Moral')], default='MORAL', max_length=10)),
                ('rfc', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido (formato SAT).'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(13)], verbose_name='RFC')),
                ('nombre_fiscal', models.CharField(help_text='Debe coincidir con el nombre registrado ante el SAT.', max_length=254, verbose_name='Nombre / Razón social (SAT)')),
                ('nombre_fiscal_normalizado', models.CharField(db_index=True, editable=False, max_length=260)),
                ('regimen_fiscal', models.CharField(help_text='Clave SAT. Ej: 601, 612, 626, etc.', max_length=3, verbose_name='Régimen fiscal (c_RegimenFiscal)')),
                ('domicilio_fiscal_cp', models.CharField(help_text='CFDI 4.0 requiere el CP del domicilio fiscal del receptor.', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'El CP debe tener 5 dígitos.')], verbose_name='Domicilio fiscal - CP (SAT)')),
                ('uso_cfdi_default', models.CharField(blank=True, help_text='Clave SAT. Ej: G03, S01, P01, etc. (opcional pero recomendado).', max_length=3, verbose_name='Uso CFDI por defecto (c_UsoCFDI)')),
                ('email_cfdi', models.EmailField(blank=True, help_text='Correo donde se enviará XML/PDF (no obligatorio para timbrar).', max_length=254, verbose_name='Email para envío CFDI')),
                ('nombre_comercial', models.CharField(blank=True, max_length=150, verbose_name='Nombre comercial')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('calle', models.CharField(blank=True, max_length=120)),
                ('num_ext', models.CharField(blank=True, max_length=20, verbose_name='No. ext.')),
                ('num_int', models.CharField(blank=True, max_length=20, verbose_name='No. int.')),
                ('colonia', models.CharField(blank=True, max_length=120)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, default='México', max_length=60)),
                ('cp', models.CharField(blank=True, max_length=5, verbose_name='CP (operativo)')),
                ('referencias', models.CharField(blank=True, max_length=200)),
                ('forma_pago_default', models.CharField(blank=True, help_text='Ej: 01, 03, 28... (opcional).', max_length=2, verbose_name='Forma de pago default (c_FormaPago)')),
                ('metodo_pago_default', models.CharField(blank=True, help_text='Ej: PUE o PPD (opcional).', max_length=3, verbose_name='Método de pago default (c_MetodoPago)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre_fiscal'],
                'indexes': [models.Index(fields=['rfc'], name='catalogos_c_rfc_1bf4f6_idx'), models.Index(fields=['nombre_fiscal_normalizado'], name='catalogos_c_nombre__0f37ec_idx')],
            },
        ),
    ]
