# Generated by Django 5.2.8 on 2026-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_almacen_costo_almacen_almacen_es_arrendado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_equipo',
            field=models.BooleanField(default=False, help_text='Indica si el producto es un equipo con número de serie'),
        ),
    ]
