# Generated by Django 5.2.8 on 2026-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_producto_es_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='tipo_costo',
            field=models.CharField(blank=True, choices=[('POR KILO', 'Por kilo'), ('POR TARIMA', 'Por tarima')], help_text='Aplica solo si el almacén es arrendado.', max_length=20, null=True),
        ),
    ]
