# Generated by Django 6.0.3 on 2026-05-12 16:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_productometricaconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productometricaconversion',
            name='cantidad_origen',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), help_text='Cantidad base de la unidad origen. Normalmente 1.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productometricaconversion',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=0, help_text='Cuánto equivale la cantidad origen en la métrica default del producto.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
