# Generated by Django 6.0.3 on 2026-05-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_alter_productometricaconversion_cantidad_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre de contacto'),
        ),
    ]
