# Generated by Django 6.0.3 on 2026-05-20 22:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_cliente_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio ponderado del inventario disponible.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Costo promedio actual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_actualizacion_precio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha última actualización precio venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha última compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Límite mínimo de venta para proteger margen.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio mínimo autorizado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultimo_costo_compra',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Último costo registrado en una entrada de inventario.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Último costo de compra'),
        ),
        migrations.CreateModel(
            name='ProductoPrecioHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_minimo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_minimo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='catalogos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de cambio de precio',
                'verbose_name_plural': 'Historial de cambios de precio',
                'ordering': ['-creado_en', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecioBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ultimo_costo_compra', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('stock_actual', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('margen_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_precios', to='catalogos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora diaria de precio',
                'verbose_name_plural': 'Bitácora diaria de precios',
                'ordering': ['-fecha', 'producto__nombre'],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
