# Generated by Django 6.0.3 on 2026-05-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_producto_costo_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='maneja_peso_variable',
            field=models.BooleanField(default=False, help_text='Actívalo cuando el producto entra por cajas con peso real variable. En entrada manual se capturarán cajas y kilos reales.', verbose_name='Maneja peso variable por caja'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
