# Generated by Django 6.0.3 on 2026-05-21 18:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_producto_maneja_peso_variable_alter_producto_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('valor', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('ENTERO', 'Entero'), ('DECIMAL', 'Decimal'), ('TEXTO', 'Texto'), ('BOOLEANO', 'Booleano')], default='TEXTO', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro de sistema',
                'verbose_name_plural': 'Parámetros de sistema',
                'ordering': ['clave'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_fiscal_cp',
            field=models.CharField(blank=True, help_text='Opcional. CFDI 4.0 lo requiere solo al facturar.', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'El CP debe tener 5 dígitos.')], verbose_name='Domicilio fiscal - CP (SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_fiscal',
            field=models.CharField(blank=True, help_text='Opcional. Debe coincidir con SAT cuando se requiera CFDI.', max_length=254, verbose_name='Nombre / Razón social (SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 - Demás ingresos'), ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 - Ingresos por Dividendos (socios y accionistas)'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 - Ingresos por intereses'), ('615', '615 - Régimen de los ingresos por obtención de premios'), ('616', '616 - Sin obligaciones fiscales'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 - Incorporación Fiscal'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 - Régimen Simplificado de Confianza')], max_length=3, verbose_name='Régimen fiscal (SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, help_text='Opcional. Capturar solo cuando el cliente requiera datos fiscales/CFDI.', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido (formato SAT).'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(13)], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productometricaconversion',
            name='cantidad_origen',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad base de la unidad origen. Normalmente 1.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productometricaconversion',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, help_text='Cuánto equivale la cantidad origen en la métrica default del producto.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productopreciobitacora',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PrecioAutorizacionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('precio_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_solicitado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADO', 'Autorizado'), ('USADO', 'Usado'), ('EXPIRADO', 'Expirado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.producto')),
                ('usuario_autoriza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_precio', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_precio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de autorización de precio',
                'verbose_name_plural': 'Tokens de autorización de precios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ClienteProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_ultimo_precio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_productos', to='catalogos.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_clientes', to='catalogos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Último precio por cliente',
                'verbose_name_plural': 'Últimos precios por cliente',
                'ordering': ['cliente__nombre_fiscal', 'producto__nombre'],
                'unique_together': {('cliente', 'producto')},
            },
        ),
    ]
