# Generated by Django 6.0.3 on 2026-05-21 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0019_parametrosistema_alter_cliente_domicilio_fiscal_cp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_fiscal', 'nombre_comercial']},
        ),
        migrations.AlterModelOptions(
            name='clienteproductoprecio',
            options={'ordering': ['cliente__nombre_fiscal', 'producto__nombre'], 'verbose_name': 'Precio por cliente', 'verbose_name_plural': 'Precios por cliente'},
        ),
        migrations.RenameField(
            model_name='clienteproductoprecio',
            old_name='usuario',
            new_name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='clienteproductoprecio',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='parametrosistema',
            name='tipo',
        ),
        migrations.AddField(
            model_name='clienteproductoprecio',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clienteproductoprecio',
            name='precio_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='domicilio_fiscal_cp',
            field=models.CharField(blank=True, help_text='CFDI 4.0 requiere el CP del domicilio fiscal del receptor.', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'El CP debe tener 5 dígitos.')], verbose_name='Domicilio fiscal - CP (SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_fiscal',
            field=models.CharField(blank=True, help_text='Debe coincidir con el nombre registrado ante el SAT.', max_length=254, verbose_name='Nombre / Razón social (SAT)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z&Ñ]{3,4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido (formato SAT).'), django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(13)], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='clienteproductoprecio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_producto', to='catalogos.cliente'),
        ),
        migrations.AlterField(
            model_name='clienteproductoprecio',
            name='fecha_ultimo_precio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clienteproductoprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_cliente', to='catalogos.producto'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='clave',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='valor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio ponderado del inventario disponible.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo promedio actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ultimo_costo_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Último costo registrado en una entrada de inventario.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Último costo de compra'),
        ),
        migrations.AlterField(
            model_name='productometricaconversion',
            name='cantidad_origen',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad base de la unidad origen. Normalmente 1.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productometricaconversion',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, help_text='Cuánto equivale la cantidad origen en la métrica default del producto.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productopreciobitacora',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productopreciobitacora',
            name='margen_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productopreciobitacora',
            name='ultimo_costo_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PrecioMenorMinimoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_precio_minimo', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_precio', to='catalogos.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_precio', to='catalogos.producto')),
                ('usuario_solicita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_precio_minimo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorización de precio menor al mínimo',
                'verbose_name_plural': 'Autorizaciones de precio menor al mínimo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.DeleteModel(
            name='PrecioAutorizacionToken',
        ),
    ]
