# Generated by Django 6.0.3 on 2026-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.CharField(choices=[('CPC', 'CPC Alimentos'), ('BAJA_BACON', 'Baja Bacon')], default='CPC', help_text='Logo default que se usará en las notas de venta del cliente.', max_length=20, verbose_name='Logo'),
        ),
    ]
