# Generated by Django 6.0.3 on 2026-06-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0022_cliente_credito_autorizacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientecreditoautorizacion',
            new_name='catalogos_c_cliente_b63cba_idx',
            old_name='catalogos_c_cliente_e4cb8c_idx',
        ),
        migrations.RenameIndex(
            model_name='clientecreditoautorizacion',
            new_name='catalogos_c_fecha_s_6a85b2_idx',
            old_name='catalogos_c_fecha_s_7696c0_idx',
        ),
    ]
