# Generated by Django 6.0.3 on 2026-06-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_cierrecosteo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cierrecosteoperiodo',
            new_name='costos_cier_periodo_5a8f08_idx',
            old_name='costos_cier_periodo_7a9f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='cierrecosteoperiodo',
            new_name='costos_cier_estado_869f93_idx',
            old_name='costos_cier_estado_1ad5d8_idx',
        ),
        migrations.RenameIndex(
            model_name='cierrecosteoproducto',
            new_name='costos_cier_cierre__faceae_idx',
            old_name='costos_cier_cierre__e08f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='cierrecosteoproducto',
            new_name='costos_cier_product_68ef07_idx',
            old_name='costos_cier_product_ef1860_idx',
        ),
        migrations.RenameIndex(
            model_name='gasto',
            new_name='costos_gast_fecha_9a038b_idx',
            old_name='costos_gast_fecha_d78658_idx',
        ),
        migrations.RenameIndex(
            model_name='gasto',
            new_name='costos_gast_periodo_4ddb13_idx',
            old_name='costos_gast_periodo_c34b1d_idx',
        ),
        migrations.RenameIndex(
            model_name='gasto',
            new_name='costos_gast_categor_a4fdf1_idx',
            old_name='costos_gast_categor_8494a7_idx',
        ),
        migrations.RenameIndex(
            model_name='gastodistribucion',
            new_name='costos_gast_gasto_i_8e716d_idx',
            old_name='costos_gast_gasto_i_d0759d_idx',
        ),
        migrations.RenameIndex(
            model_name='gastodistribucion',
            new_name='costos_gast_product_d7ef36_idx',
            old_name='costos_gast_product_5c0aca_idx',
        ),
        migrations.RenameIndex(
            model_name='gastodistribucion',
            new_name='costos_gast_metodo__7d1942_idx',
            old_name='costos_gast_metodo__1486e3_idx',
        ),
        migrations.AlterField(
            model_name='gasto',
            name='metodo_distribucion',
            field=models.CharField(choices=[('KG_VENDIDO', 'Por kg vendido'), ('IMPORTE_VENTA', 'Por importe vendido'), ('KG_COMPRADO', 'Por kg comprado'), ('COSTO_COMPRA', 'Por costo de compra'), ('DIRECTO_ENTRADA', 'Directo a entrada'), ('MANUAL', 'Manual por producto'), ('NO_DISTRIBUIR', 'No distribuir')], default='KG_VENDIDO', help_text='Método que se usará para distribuir automáticamente el gasto al costeo real al aplicarlo.', max_length=25, verbose_name='Método de distribución'),
        ),
    ]
