# Generated by Django 6.0.3 on 2026-06-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0006_gastodistribucion_ventas'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastodistribucion',
            name='salida_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_distribuidos', to='ventas.notaventadetalle', verbose_name='Detalle de salida'),
        ),
    ]
