# Generated by Django 6.0.3 on 2026-06-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0008_flujo_costos_simplificado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='almacenajeproductoperiodo',
            new_name='costos_alma_periodo_face77_idx',
            old_name='costos_alm_periodo_1be8d4_idx',
        ),
        migrations.RenameIndex(
            model_name='almacenajeproductoperiodo',
            new_name='costos_alma_almacen_023c6c_idx',
            old_name='costos_alm_almacen_245c36_idx',
        ),
        migrations.RenameIndex(
            model_name='gastoperiodo',
            new_name='costos_gast_periodo_0d60cd_idx',
            old_name='costos_gas_periodo_2b9b57_idx',
        ),
        migrations.RenameIndex(
            model_name='gastoperiodo',
            new_name='costos_gast_tipo_ga_506e4e_idx',
            old_name='costos_gas_tipo_ga_c6bd91_idx',
        ),
        migrations.RenameIndex(
            model_name='periodocosteo',
            new_name='costos_peri_fecha_i_e2a263_idx',
            old_name='costos_per_fecha_i_9b8f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='periodocosteo',
            new_name='costos_peri_estado_33f9d9_idx',
            old_name='costos_per_estado_589d62_idx',
        ),
        migrations.RenameIndex(
            model_name='resultadocostoproducto',
            new_name='costos_resu_periodo_4ac69f_idx',
            old_name='costos_res_periodo_53c773_idx',
        ),
        migrations.RenameIndex(
            model_name='resultadocostoproducto',
            new_name='costos_resu_product_15ddf4_idx',
            old_name='costos_res_product_d43b82_idx',
        ),
        migrations.RenameIndex(
            model_name='resultadocostoproducto',
            new_name='costos_resu_margen__8e8235_idx',
            old_name='costos_res_margen__997d3d_idx',
        ),
    ]
