# Generated by Django 5.2.8 on 2025-12-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_proyecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Proyectos',
        ),
    ]
