# Generated by Django 5.2.8 on 2025-12-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_rename_proyecto_proyectos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Proyecto',
        ),
    ]
