# Generated by Django 5.2.8 on 2025-12-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_rename_proyectos_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='apodo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
