# Generated by Django 5.2.8 on 2026-01-13 22:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_almacen_alter_cliente_forma_pago_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='costo_almacen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aplica solo si el almacén es arrendado.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='almacen',
            name='es_arrendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tipo_costo',
            field=models.CharField(blank=True, choices=[('MENSUAL', 'Mensual'), ('SEMANAL', 'Semanal'), ('ANUAL', 'Anual'), ('UNICO', 'Único')], help_text='Aplica solo si el almacén es arrendado.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='vencimiento_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Cada cuántos días vence el pago (solo arrendado).', null=True),
        ),
    ]
