# Generated by Django 5.2.8 on 2025-12-08 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('MAN', 'Entrada nota / remisión'), ('AJP', 'Ajuste de inventario')], max_length=3, verbose_name='Tipo de entrada')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrada de inventario',
                'verbose_name_plural': 'Entradas de inventario',
                'ordering': ['-fecha', '-folio'],
            },
        ),
        migrations.CreateModel(
            name='EntradaInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo unitario')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.entradainventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de entrada',
                'verbose_name_plural': 'Detalles de entradas',
            },
        ),
    ]
