# Generated by Django 5.2.8 on 2025-12-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventario',
            name='xml_contenido',
            field=models.TextField(blank=True, verbose_name='Contenido XML'),
        ),
    ]
