# Generated by Django 5.2.8 on 2025-12-16 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_proveedor'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True, verbose_name='Folio')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('VTA', 'Salida por venta'), ('CON', 'Consumo interno / servicio'), ('MRM', 'Merma / daño / robo'), ('DEV', 'Devolución a proveedor'), ('AJN', 'Ajuste negativo (disminuye stock)'), ('TRS', 'Salida por traslado')], max_length=3, verbose_name='Tipo de salida')),
                ('cliente', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('documento_referencia', models.CharField(blank=True, max_length=60, verbose_name='Documento referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salida de inventario',
                'verbose_name_plural': 'Salidas de inventario',
                'ordering': ['-fecha', '-folio'],
            },
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='tipo',
            field=models.CharField(choices=[('MAN', 'Entrada manual (nota / remisión)'), ('AJP', 'Ajuste positivo (incrementa stock)'), ('TRE', 'Entrada por traslado')], max_length=3, verbose_name='Tipo de entrada'),
        ),
        migrations.CreateModel(
            name='SalidaInventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.salidainventario')),
            ],
            options={
                'verbose_name': 'Detalle de salida',
                'verbose_name_plural': 'Detalles de salidas',
            },
        ),
    ]
