# Generated by Django 5.2.8 on 2025-12-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_salidainventario_alter_entradainventario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventario',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo'),
        ),
    ]
