# Generated by Django 5.2.8 on 2025-12-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_entradainventario_motivo_salidainventario_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainventario',
            name='tipo',
            field=models.CharField(choices=[('OCF', 'Factura'), ('MAN', 'Entrada nota / remisión'), ('AJP', 'Ajuste'), ('TRE', 'Entrada por traspaso')], max_length=3, verbose_name='Tipo de entrada'),
        ),
    ]
