# Generated by Django 5.2.8 on 2025-12-30 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_proyecto_apodo_proyecto_direccion_and_more'),
        ('inventarios', '0005_alter_entradainventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_inventario', to='catalogos.proyecto'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='tipo',
            field=models.CharField(choices=[('VTA', 'Salida por venta'), ('CON', 'Consumo interno / servicio'), ('MRM', 'Merma / daño / robo'), ('DEV', 'Devolución a proveedor'), ('AJN', 'Ajuste negativo (disminuye stock)'), ('TRS', 'Salida por traslado'), ('PRY', 'Salida por poryecto')], max_length=3, verbose_name='Tipo de salida'),
        ),
    ]
