# Generated by Django 5.2.8 on 2026-01-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_almacen_alter_cliente_forma_pago_default_and_more'),
        ('inventarios', '0006_salidainventario_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalogos.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalogos.producto')),
            ],
            options={
                'verbose_name': 'Stock por almacén',
                'verbose_name_plural': 'Stocks por almacén',
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
