# Generated by Django 5.2.8 on 2026-01-09 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_almacen_alter_cliente_forma_pago_default_and_more'),
        ('inventarios', '0007_inventariostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_inventario', to='catalogos.almacen'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_inventario', to='catalogos.almacen'),
        ),
    ]
