# Generated by Django 5.2.8 on 2026-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_entradainventario_almacen_salidainventario_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainventario',
            name='tipo',
            field=models.CharField(choices=[('OCF', 'Factura'), ('MAN', 'Entrada nota / remisión'), ('AJP', 'Ajuste'), ('TRE', 'Entrada por traspaso'), ('RTN', 'Retorno')], max_length=3, verbose_name='Tipo de entrada'),
        ),
    ]
