# Generated by Django 5.2.8 on 2026-01-15 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_almacen_tipo_costo'),
        ('inventarios', '0009_alter_entradainventario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventario',
            name='documento_referencia',
            field=models.CharField(blank=True, help_text='Ej: Nota, remisión, devolución, etc.', max_length=60, verbose_name='Documento referencia'),
        ),
        migrations.AddField(
            model_name='entradainventario',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retornos_inventario', to='catalogos.proyecto'),
        ),
    ]
