# Generated by Django 5.2.8 on 2026-01-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_almacen_tipo_costo'),
        ('inventarios', '0010_entradainventario_documento_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_detalle', to='catalogos.almacen'),
        ),
    ]
