# Generated by Django 5.2.8 on 2026-01-24 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_almacen_tipo_costo'),
        ('inventarios', '0011_entradainventariodetalle_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainventario',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.proveedor'),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='tipo',
            field=models.CharField(choices=[('MAN', 'Entrada nota / remisión'), ('AJP', 'Ajuste (aumenta stock)'), ('TRE', 'Entrada por traspaso'), ('RTN', 'Retorno')], max_length=3, verbose_name='Tipo de entrada'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='tipo',
            field=models.CharField(choices=[('VTA', 'Salida por venta'), ('CON', 'Consumo interno / servicio'), ('MRM', 'Merma / daño / robo'), ('DEV', 'Devolución a proveedor'), ('AJN', 'Ajuste (disminuye stock)'), ('TRS', 'Salida por traslado'), ('PRY', 'Salida por poryecto')], max_length=3, verbose_name='Tipo de salida'),
        ),
    ]
