# Generated by Django 5.2.8 on 2026-01-24 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_alter_almacen_tipo_costo'),
        ('inventarios', '0012_alter_entradainventario_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradainventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.proveedor'),
        ),
    ]
