# Generated by Django 6.0.3 on 2026-05-12 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0015_alter_productometricaconversion_cantidad_origen_and_more'),
        ('inventarios', '0014_alter_entradainventario_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada en'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activa'), ('CAN', 'Cancelada')], db_index=True, default='ACT', max_length=3, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén principal del renglón. Para ventas surtidas de varios almacenes usar asignaciones.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_detalle', to='catalogos.almacen'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='presentacion_nombre',
            field=models.CharField(blank=True, help_text='Ej: Kilos, Caja 20 kg, Caja 10 kg.', max_length=120, verbose_name='Presentación'),
        ),
        migrations.CreateModel(
            name='SalidaInventarioDetalleAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_asignadas', to='catalogos.almacen')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventarios.salidainventariodetalle')),
            ],
            options={
                'verbose_name': 'Asignación de salida por almacén',
                'verbose_name_plural': 'Asignaciones de salida por almacén',
            },
        ),
    ]
