# Generated by Django 6.0.3 on 2026-05-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0015_salidainventario_cancelada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad original capturada por el usuario. Ej: 2 cajas.', max_digits=12, null=True, verbose_name='Cantidad vendida en presentación'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='presentacion_conversion_id',
            field=models.CharField(blank=True, help_text='Identificador de la presentación/conversión usada al capturar la venta.', max_length=50, verbose_name='ID de conversión usada'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='presentacion_equivalencia_texto',
            field=models.CharField(blank=True, help_text='Texto histórico de la equivalencia aplicada. Ej: 1 Caja 20 kg = 20 kg.', max_length=160, verbose_name='Equivalencia usada'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='presentacion_factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de métrica base que descuenta cada unidad de presentación. Ej: 20 kg por caja.', max_digits=12, null=True, verbose_name='Factor de conversión a métrica base'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='presentacion_metrica_default',
            field=models.CharField(blank=True, help_text='Métrica en la que se descuenta inventario. Ej: kg.', max_length=50, verbose_name='Métrica base'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad ya convertida a la métrica base del inventario.', max_digits=12, verbose_name='Cantidad descontada de inventario'),
        ),
    ]
