# Generated by Django 6.0.3 on 2026-05-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0016_salidainventariodetalle_cantidad_presentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad original capturada por el usuario. Ej: 2 cajas.', max_digits=12, null=True, verbose_name='Cantidad capturada en presentación'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='presentacion_conversion_id',
            field=models.CharField(blank=True, help_text='Identificador de la presentación/conversión usada al capturar la entrada.', max_length=50, verbose_name='ID de conversión usada'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='presentacion_equivalencia_texto',
            field=models.CharField(blank=True, help_text='Texto histórico de la equivalencia aplicada. Ej: 1 Caja 20 kg = 20 kg.', max_length=160, verbose_name='Equivalencia usada'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='presentacion_factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de métrica base que entra por cada unidad de presentación. Ej: 20 kg por caja.', max_digits=12, null=True, verbose_name='Factor de conversión a métrica base'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='presentacion_metrica_default',
            field=models.CharField(blank=True, help_text='Métrica en la que se incrementa inventario. Ej: kg.', max_length=50, verbose_name='Métrica base'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='presentacion_nombre',
            field=models.CharField(blank=True, help_text='Ej: Kilos, Caja 20 kg, Caja 10 kg.', max_length=120, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='cliente_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contacto del cliente para esta venta'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='cliente_direccion',
            field=models.TextField(blank=True, verbose_name='Dirección del cliente para esta venta'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad ya convertida a la métrica base del inventario.', max_digits=12, verbose_name='Cantidad agregada al inventario'),
        ),
    ]
