# Generated by Django 6.0.3 on 2026-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0017_entradainventariodetalle_cantidad_presentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariostock',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio ponderado del producto en este almacén.', max_digits=14, verbose_name='Costo promedio'),
        ),
        migrations.AddField(
            model_name='salidainventariodetalle',
            name='costo_unitario_aplicado',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Costo promedio guardado al momento de vender para conservar margen histórico.', max_digits=12, verbose_name='Costo unitario aplicado'),
        ),
    ]
