# Generated by Django 6.0.3 on 2026-05-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0018_inventariostock_costo_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='cantidad_cajas',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Número de cajas recibidas para productos con peso variable.', max_digits=14, verbose_name='Cantidad de cajas'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de la línea al momento de capturar la entrada.', max_digits=14, verbose_name='Costo total'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='es_peso_variable',
            field=models.BooleanField(default=False, help_text='Indica que la cantidad de inventario se capturó con kilos reales y cajas informativas.', verbose_name='Entrada con peso variable'),
        ),
        migrations.AddField(
            model_name='entradainventariodetalle',
            name='kilos_reales',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Kilos reales recibidos para productos con peso variable.', max_digits=14, verbose_name='Kilos reales'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad ya convertida a la métrica base del inventario.', max_digits=14, verbose_name='Cantidad agregada al inventario'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad original capturada por el usuario. Ej: 2 cajas.', max_digits=14, null=True, verbose_name='Cantidad capturada en presentación'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad ya convertida a la métrica base del inventario.', max_digits=14, verbose_name='Cantidad descontada de inventario'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad original capturada por el usuario. Ej: 2 cajas.', max_digits=14, null=True, verbose_name='Cantidad vendida en presentación'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetallealmacen',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad'),
        ),
    ]
