# Generated by Django 6.0.3 on 2026-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0019_entradainventariodetalle_cantidad_cajas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='forma_pago_venta',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10, verbose_name='Forma de pago de la nota'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad ya convertida a la métrica base del inventario.', max_digits=14, verbose_name='Cantidad agregada al inventario'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='cantidad_cajas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Número de cajas recibidas para productos con peso variable.', max_digits=14, verbose_name='Cantidad de cajas'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad original capturada por el usuario. Ej: 2 cajas.', max_digits=14, null=True, verbose_name='Cantidad capturada en presentación'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='kilos_reales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kilos reales recibidos para productos con peso variable.', max_digits=14, verbose_name='Kilos reales'),
        ),
        migrations.AlterField(
            model_name='entradainventariodetalle',
            name='presentacion_factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de métrica base que entra por cada unidad de presentación. Ej: 20 kg por caja.', max_digits=12, null=True, verbose_name='Factor de conversión a métrica base'),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio ponderado del producto en este almacén.', max_digits=14, verbose_name='Costo promedio'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad ya convertida a la métrica base del inventario.', max_digits=14, verbose_name='Cantidad descontada de inventario'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad original capturada por el usuario. Ej: 2 cajas.', max_digits=14, null=True, verbose_name='Cantidad vendida en presentación'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='costo_unitario_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio guardado al momento de vender para conservar margen histórico.', max_digits=12, verbose_name='Costo unitario aplicado'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetalle',
            name='presentacion_factor_conversion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de métrica base que descuenta cada unidad de presentación. Ej: 20 kg por caja.', max_digits=12, null=True, verbose_name='Factor de conversión a métrica base'),
        ),
        migrations.AlterField(
            model_name='salidainventariodetallealmacen',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Cantidad'),
        ),
    ]
