# Generated by Django 6.0.3 on 2026-05-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_alter_cliente_options_and_more'),
        ('inventarios', '0020_salidainventario_forma_pago_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='cliente_ref',
            field=models.ForeignKey(blank=True, help_text='Cliente del catálogo usado para historial de precios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_inventario', to='catalogos.cliente'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='forma_pago_venta',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10, verbose_name='Forma de pago de venta'),
        ),
    ]
