# Generated by Django 6.0.3 on 2026-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0021_salidainventario_cliente_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidainventario',
            name='tipo',
            field=models.CharField(choices=[('VTA', 'Salida por venta'), ('AJN', 'Ajuste (disminuye stock)')], max_length=3, verbose_name='Tipo de salida'),
        ),
    ]
