# Generated by Django 6.0.3 on 2026-05-25 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0022_alter_salidainventario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='editada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editada en'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='editada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_venta_editadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='estado_pago',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PEND', 'Pendiente de pago')], db_index=True, default='PEND', help_text='Estado administrativo de pago de la nota; no depende de la forma de pago.', max_length=4, verbose_name='Estado de pago'),
        ),
    ]
