# Generated by Django 6.0.3 on 2026-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0024_alter_salidainventario_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidainventario',
            name='logo_nota',
            field=models.CharField(choices=[('REGIMAR', 'Regimar')], default='REGIMAR', help_text='Logo usado históricamente para imprimir esta nota de venta.', max_length=20, verbose_name='Logo'),
        ),
    ]
