# Generated by ChatGPT on 2026-06-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0021_cliente_logo'),
        ('inventarios', '0025_salidainventario_logo_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradainventario',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, help_text='Almacén destino cuando el movimiento corresponde a un traspaso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_traspaso_destino', to='catalogos.almacen'),
        ),
        migrations.AddField(
            model_name='entradainventario',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, help_text='Almacén origen cuando el movimiento corresponde a un traspaso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_traspaso_origen', to='catalogos.almacen'),
        ),
        migrations.AddField(
            model_name='entradainventario',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento de inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_inventario_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, help_text='Almacén destino cuando el movimiento corresponde a un traspaso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_traspaso_destino', to='catalogos.almacen'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, help_text='Almacén origen cuando el movimiento corresponde a un traspaso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_traspaso_origen', to='catalogos.almacen'),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento de inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_inventario_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='tipo',
            field=models.CharField(choices=[('VTA', 'Salida por venta'), ('AJN', 'Ajuste (disminuye stock)'), ('TRS', 'Salida por traspaso')], max_length=3, verbose_name='Tipo de salida'),
        ),
    ]
