# Generated by Django 6.0.3 on 2026-05-27 18:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionpreciodetalle',
            name='cantidad_cajas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad informativa de cajas/piezas cuando aplique. No afecta inventario.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='cotizacionpreciodetalle',
            name='cantidad_estimada',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad estimada en la unidad base del producto. No afecta inventario.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='cotizacionpreciodetalle',
            name='importe_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cotizacionpreciodetalle',
            name='utilidad_total_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
