# Generated by Django 6.0.3 on 2026-05-28 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0020_alter_cliente_options_and_more'),
        ('cotizaciones', '0003_parametro_vigencia_cotizaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionprecio',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente existente del sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_precio', to='catalogos.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacionprecio',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacionprecio',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
